{{- $projectName := .Values.global.project_name}}
{{- with .Values}}
# service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name}}
  labels:
    name: {{ .service.name}}
    app: {{ $projectName}}
spec:
  ports:
  - name: {{ .containers.main.name}}
    port: {{ .containers.main.containerPort}}
  clusterIP: None
  selector:
    name: {{ .deploy_name}}
    app: {{ $projectName}}
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the primary: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name}}-read
  labels:
    name: {{ .service.name}}-read
    app: {{ $projectName}}
spec:
  ports:
  - name: {{ .containers.main.name}}
    port: {{ .containers.main.containerPort}}
  selector:
    name: {{ .deploy_name}}
    app: {{ $projectName}}
{{- end}}