apiVersion: v2
name: linotp_chart
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "2.2.9"
dependencies:
  - name: linotp
    version: 1.0.0
keywords:
  - 2FA
  - Radius
  - OTP
  - LinOTP
  - Freeradius

maintainers:
  - name: Mahyar Nazari
    url: https://github.com/mahyarnzi/linotp
    email: mahyar.nzi@gmail.com