global:
  project_name: linotp

linotp:
  replicas: 1
  deploy_name: linotp-app
  persistent_volume:
    enabled: false
  storage:
    name: linotp-pvc
    capacity: 1Gi
    accessModes: ReadWriteOnce
    storageClassName: csi-s3
  image: soffid/linotp:latest
  imagePullPolicy: IfNotPresent
  resource:
    memory:
      need: 1Gi
      limit: 2Gi
    cpu:
      need: 1
      limit: 2
  secret:
    name: linotp-secret
    data:
      - key: key
        value: value
  configMap:
    name: linotp-config
    data:
      - key: key
        value: value
  volume:
    name: linotp-log
    mountPath: /var/log/apache2
    subPath: apache2
  service:
    - name: linotp-app
      type: ClusterIP
      ports:
        port: 443
        targetPort: 443
        protocol: TCP
    - name: linotp-app-publish
      type: NodePort
      ports:
        port: 443
        targetPort: 443
        nodePort: 30000
        protocol: TCP

  mysql:
    replicas: 2
    deploy_name: linotp-db
    storage:
      name: data
      capacity: 5Gi
      accessModes: ReadWriteOnce
      storageClassName: csi-s3
    containers:
      init:
        image: mysql:5.6
      clone:
        image: gcr.io/google-samples/xtrabackup:1.0
      main:
        image: mysql:5.6
        resource:
          memory:
            need: 1Gi
            limit: 2Gi
          cpu:
            need: 500m
            limit: 2
      backup:
        image: gcr.io/google-samples/xtrabackup:1.0
    configMap:
      name: mysql-config
    secret:
      name: mysql-secret
      data:
        - key: key
          value: value
    service:
      name: linotp-db

radius:
  replicas: 1
  deploy_name: freeradius-deploy
  pod_name: freeradius-pod
  container_name: freeradius
  image: mahyarnzi/linotp-freeradius:latest
  imagePullPolicy: IfNotPresent
  resource:
    memory:
      need: 512Mi
      limit: 1Gi
    cpu:
      need: 0.5
      limit: 1
  containerPort: 1812
  containerProtocol: UDP
  secret:
    name: freeradius-secret
    data:
      - key: key
        value: value
  configMap:
    name: freeradius-config
    data:
      - key: key
        value: value
  service:
    - name: freeradius-publish
      annotations:
        - key: ametallb.universe.tf/allow-shared-ip
          value: true
      type: NodePort
      ports:
        port: 1812
        targetPort: 1812
        nodePort: 30001
        protocol: UDP