replicas: 1
deploy_name: mysql
containers:
  init:
    name: init-mysql
    image: mysql:5.6
    imagePullPolicy: IfNotPresent
  clone:
    name: clone-mysql
    image: gcr.io/google-samples/xtrabackup:1.0
    imagePullPolicy: IfNotPresent
  main:
    name: mysql
    image: mysql:5.6
    imagePullPolicy: IfNotPresent
    resource:
      memory:
        need: 1Gi
        limit: "2Gi"
      cpu:
        need: 500m
        limit: 2
    containerPort: 3306
    containerProtocol: TCP
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 2
      timeoutSeconds: 1
  backup:
    name: xtrabackup
    image: gcr.io/google-samples/xtrabackup:1.0
    imagePullPolicy: IfNotPresent
    containerPort: 3307
    containerProtocol: TCP
    resource:
      memory:
        need: 100Mi
        limit: 500Mi
      cpu:
        need: 100m
        limit: 500m
storage:
      name: mysql-pvc
      capacity: 1Gi
      accessModes: ReadWriteOnce
      storageClassName: csi-s3
service:
  name: mysql
  
