application:
  secret:
    name: linotp-secret
    data:
      - key: MARIADB_PASS
        value: cGFzc3dvcmQ=
      - key: ADMIN_PASSWORD
        value: cGFzc3dvcmQ=
  configMap:
    name: linotp-config
    data:
      - key: MARIADB_HOST
        value: linotp-db

database:
  secret:
    name: mysql-secret
    data:
      - key: MYSQL_ROOT_PASSWORD
        value: cGFzc3dvcmQ=
      - key: MYSQL_DATABASE
        value: bGlub3Rw

radius:
  secret:
    name: freeradius-secret
    data:
      - key: RADIUS_CLIENTS
        value: c2VjcmV0QDAuMC4wLjAvMA==
  configMap:
    name: freeradius-config
    data:
      - key: RADIUS_LISTEN_IP
        value: "*"