project_name: linotp
product_mode:
  enabled: false

namespaces:
  - name: linotp-dev
  - name: linotp-prod

database:
  replicas: 1
  deploy_name: linotp-db
  storage:
    name: mysql-pvc
    capacity: 10Gi
    accessModes: ReadWriteOnce
    storageClassName: csi-s3
  pod_name: mysql-pod
  container_name: mysql
  containerPort: 3306
  containerProtocol: TCP
  image: mysql:5.6
  imagePullPolicy: IfNotPresent
  resource:
    memory:
      need: 1Gi
      limit: 2Gi
    cpu:
      need: 1
      limit: 2
  secret:
    name: mysql-secret
    data:
      - key: key
        value: value
  volume:
    name: linotp-data
    mountPath: /var/lib/mysql
    subPath: "mysql"
  service:
    - name: linotp-db
      type: ClusterIP
      ports:
        port: 3306
        targetPort: 3306
        protocol: TCP

application:
  replicas: 1
  deploy_name: linotp-app
  storage:
    name: linotp-pvc
    capacity: 1Gi
    accessModes: ReadWriteOnce
    storageClassName: csi-s3
  pod_name: linotp-pod
  container_name: linotp
  image: soffid/linotp:latest
  imagePullPolicy: IfNotPresent
  resource:
    memory:
      need: 1Gi
      limit: 2Gi
    cpu:
      need: 1
      limit: 2
  containerPort: 443
  containerProtocol: TCP
  secret:
    name: linotp-secret
    data:
      - key: key
        value: value
  configMap:
    name: linotp-config
    data:
      - key: key
        value: value
  volume:
    name: linotp-log
    mountPath: /var/log/apache2
    subPath: apache2
  service:
    - name: linotp-app
      type: ClusterIP
      ports:
        port: 443
        targetPort: 443
        protocol: TCP
    - name: linotp-app-publish
      type: NodePort
      ports:
        port: 443
        targetPort: 443
        nodePort: 30000
        protocol: TCP

radius:
  replicas: 0
  deploy_name: freeradius-deploy
  pod_name: freeradius-pod
  container_name: freeradius
  image: mahyarnzi/linotp-freeradius:latest
  imagePullPolicy: IfNotPresent
  resource:
    memory:
      need: 512Mi
      limit: 1Gi
    cpu:
      need: 0.5
      limit: 1
  containerPort: 1812
  containerProtocol: UDP
  secret:
    name: freeradius-secret
    data:
      - key: key
        value: value
  configMap:
    name: freeradius-config
    data:
      - key: key
        value: value
  service:
    - name: freeradius-publish
      allow_shared_ip: true
      type: NodePort
      ports:
        port: 1812
        targetPort: 1812
        nodePort: 30001
        protocol: UDP