{{- $projectName := .Values.global.project_name}}
{{- with .Values}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .deploy_name}}
  labels:
    name: {{ .deploy_name}}
    app: {{ $projectName}}
spec:
  replicas: {{ .replicas}}
  selector:
    matchLabels:
      name: {{ .pod_name}}
      app: {{ $projectName}}
  template:
    metadata:
      name: {{ .pod_name}}
      labels:
        name: {{ .pod_name }}
        app: {{ $projectName }}
    spec:
      containers:
        - name: {{ .container_name}}
          image: {{ .image}}
          imagePullPolicy: {{ .imagePullPolicy}}
          resources:
            requests:
              memory: {{ .resource.memory.need }}
              cpu: {{ .resource.cpu.need }}
            limits:
              memory: {{ .resource.memory.limit}}
              cpu: {{ .resource.cpu.limit }}
          ports:
            - containerPort: {{ .containerPort}}
              protocol: {{ .containerProtocol}}
          envFrom:
            - secretRef:
                name: {{ .secret.name}}
          {{- if .persistent_volume.enabled }}
          volumeMounts:
            - mountPath: {{ .volume.mountPath }}
              subPath: {{ .volume.subPath}}
              name: {{ .volume.name}}
          {{- end}}
      {{- if .persistent_volume.enabled }}
      volumes:
        - name: {{ .volume.name}}
          persistentVolumeClaim:
            claimName: {{ .storage.name}}
      {{- end}}
{{- end}}