apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  # Namespace depends on the configuration in the storageclass.yaml
  namespace: kube-system
stringData:
  accessKeyID: zQTapLNQs72nHUVa
  secretAccessKey: 4c46oNcZCEXnwtJKNB0gCG3YF9AWHyzX
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: http://192.168.22.213:9000
  # If not on S3, set it to ""
  region: ""
