apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeradius-deploy
  labels:
    name: freeradius-deploy
    app: linotp
  namespace: linotp-dev

spec:
  replicas: 1
  selector:
    matchLabels:
      name: freeradius-pod
      app: linotp

  template:
    metadata:
      name: freeradius-pod
      labels:
        name: freeradius-pod
        app: linotp
      namespace: linotp-dev

    spec:
      containers:
        - name: freeradius
          image: mahyarnzi/linotp-freeradius:v1
          resources:
            requests:
              memory: "512Mi"
              cpu: 0.5

            limits:
              memory: "1Gi"
              cpu: 1

          envFrom:
            - configMapRef:
                name: freeradius-config

            - secretRef:
                name: freeradius-secret

          ports:
            - containerPort: 1812
              protocol: UDP

          volumeMounts:
            - mountPath: /etc/linotp2
              name: freeradius-data

      imagePullSecrets:
        - name: regcred

      volumes:
        - name: freeradius-data
          hostPath:
            path: /data/freeradius
            type: Directory

      nodeName: worker1