apiVersion: v1
kind: Service
metadata:
  name: linotp-app
  labels:
    name: linotp-app
    app: linotp
  namespace: linotp-dev

spec:
  type: ClusterIP
  selector:
    name: linotp-pod

  ports:
    - port: 443
      targetPort: 443
