apiVersion: v1
kind: Pod
metadata:
  name: linotp-pod
  labels:
    name: linotp-pod
    app: linotp
  namespace: linotp-dev

spec:
  containers:
    - name: linotp
      image: soffid/linotp:latest
      resources:
        requests:
          memory: "1Gi"
          cpu: 1

        limits:
          memory: "2Gi"
          cpu: 2

      ports:
        - containerPort: 443

      envFrom:
        - secretRef:
            name: linotp-secret

        - configMapRef:
            name: linotp-config