apiVersion: v1
kind: Service
metadata:
  name: linotp-app-publish
  labels:
    name: linotp-app-publish
    app: linotp

spec:
  type: NodePort
  selector:
    name: linotp-pod

  ports:
    - port: 443
      targetPort: 443
      nodePort: 30000