
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
    app: linotp

spec:
  containers:
    - name: mysql
      image: mysql:5.6

      ports:
        - containerPort: 3306

      env:
        - name: MYSQL_DATABASE
          value: linotp

        - name: MYSQL_ROOT_PASSWORD
          value: password

      volumeMounts:
        - mountPath: /var/lib/mysql
          name: linotp-data

  volumes:
    - name: linotp-data
      hostPath:
        path: /data/database
        type: Directory

  nodeName: worker1
