
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
    app: linotp
  namespace: linotp-dev

spec:
  containers:
    - name: mysql
      image: mysql:5.6
      resources:
        requests:
          memory: "1Gi"
          cpu: 1

        limits:
          memory: "2Gi"
          cpu: 2

      ports:
        - containerPort: 3306

      envFrom:
        - secretRef:
            name: mysql-secret

      volumeMounts:
        - mountPath: /var/lib/mysql
          name: linotp-data

  volumes:
    - name: linotp-data
      hostPath:
        path: /data/database
        type: Directory

  nodeName: worker1
