apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
    app: linotp
  namespace: linotp-dev

spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
      app: linotp

  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
        app: linotp
      namespace: linotp-dev

    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          resources:
            requests:
              memory: "1Gi"
              cpu: 1

            limits:
              memory: "2Gi"
              cpu: 2

          ports:
            - containerPort: 3306

          envFrom:
            - secretRef:
                name: mysql-secret

          volumeMounts:
            - mountPath: /var/lib/mysql
              name: linotp-data

      volumes:
        - name: linotp-data
          hostPath:
            path: /data/database
            type: Directory

      nodeName: worker1

---
apiVersion: v1
kind: Service
metadata:
  name: linotp-db
  labels:
    name: linotp-db
    app: linotp
  namespace: linotp-dev

spec:
  type: ClusterIP
  selector:
    name: mysql-pod

  ports:
    - port: 3306
      targetPort: 3306