apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linotp-pvc
  namespace: linotp-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-s3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linotp-deploy
  labels:
    name: linotp-deploy
    app: linotp
  namespace: linotp-dev

spec:
  replicas: 1
  selector:
    matchLabels:
      name: linotp-pod
      app: linotp

  template:
    metadata:
      name: linotp-pod
      labels:
        name: linotp-pod
        app: linotp
      namespace: linotp-dev

    spec:
      containers:
        - name: linotp
          image: soffid/linotp:latest
          resources:
            requests:
              memory: "1Gi"
              cpu: 1

            limits:
              memory: "2Gi"
              cpu: 2

          ports:
            - containerPort: 443

          envFrom:
            - secretRef:
                name: linotp-secret

            - configMapRef:
                name: linotp-config

          volumeMounts:
            - mountPath: /var/log/apache2
              subPath: apache2
              name: linotp-log

      volumes:
        - name: linotp-log
          persistentVolumeClaim:
            claimName: linotp-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: linotp-app
  labels:
    name: linotp-app
    app: linotp
  namespace: linotp-dev

spec:
  type: ClusterIP
  selector:
    name: linotp-pod

  ports:
    - port: 443
      targetPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: linotp-app-publish
  labels:
    name: linotp-app-publish
    app: linotp
  namespace: linotp-dev

spec:
  type: NodePort
  selector:
    name: linotp-pod

  ports:
    - port: 443
      targetPort: 443
      nodePort: 30000