apiVersion: v2
name: mysql
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "5.6.0"
keywords:
- database
- mysql
maintainers:
- name: Mahyar Nazari
  url: https://github.com/mahyarnzi/linotp
  email: mahyar.nzi@gmail.com