{{- with .Values.application}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .storage.name}}
spec:
  accessModes:
  - {{ .storage.accessModes}}
  resources:
    requests:
      storage: {{ .storage.capacity}}
  storageClassName: {{ .storage.storageClassName}}
{{- end}}